export enum Location {
   Afghanistan = 'AF',
   'Aland Islands' = 'AX',
   Albania = 'AL',
   Algeria = 'DZ',
   'American Samoa' = 'AS',
   Andorra = 'AD',
   Angola = 'AO',
   Anguilla = 'AI',
   Antarctica = 'AQ',
   'Antigua and Barbuda' = 'AG',
   Argentina = 'AR',
   Armenia = 'AM',
   Aruba = 'AW',
   Australia = 'AU',
   Austria = 'AT',
   Azerbaijan = 'AZ',
   Bahamas = 'BS',
   Bahrain = 'BH',
   Bangladesh = 'BD',
   Barbados = 'BB',
   Belarus = 'BY',
   Belgium = 'BE',
   Belize = 'BZ',
   Benin = 'BJ',
   Bermuda = 'BM',
   Bhutan = 'BT',
   Bolivia = 'BO',
   'Bonaire Sint Eustatius and Saba' = 'BQ',
   'Bosnia and Herzegovina' = 'BA',
   Botswana = 'BW',
   'Bouvet Island' = 'BV',
   Brazil = 'BR',
   'British Indian Ocean Territory' = 'IO',
   'Brunei' = 'BN',
   Bulgaria = 'BG',
   'Burkina Faso' = 'BF',
   Burundi = 'BI',
   Cambodia = 'KH',
   Cameroon = 'CM',
   Canada = 'CA',
   'Cape Verde' = 'CV',
   'Cayman Islands' = 'KY',
   'Central African Republic' = 'CF',
   Chad = 'TD',
   Chile = 'CL',
   China = 'CN',
   'Christmas Island' = 'CX',
   'Cocos Keeling Islands' = 'CC',
   Colombia = 'CO',
   Comoros = 'KM',
   Congo = 'CG',
   'Democratic Republic of Congo' = 'CD',
   'Cook Islands' = 'CK',
   'Costa Rica' = 'CR',
   "Cote d'Ivoire" = 'CI',
   Croatia = 'HR',
   Cuba = 'CU',
   Curacao = 'CW',
   Cyprus = 'CY',
   'Czech Republic' = 'CZ',
   Denmark = 'DK',
   Djibouti = 'DJ',
   Dominica = 'DM',
   'Dominican Republic' = 'DO',
   Ecuador = 'EC',
   Egypt = 'EG',
   'El Salvador' = 'SV',
   'Equatorial Guinea' = 'GQ',
   Eritrea = 'ER',
   Estonia = 'EE',
   Ethiopia = 'ET',
   'Falkland Islands Malvinas' = 'FK',
   'Faroe Islands' = 'FO',
   Fiji = 'FJ',
   Finland = 'FI',
   France = 'FR',
   'French Guiana' = 'GF',
   'French Polynesia' = 'PF',
   'French Southern Territories' = 'TF',
   Gabon = 'GA',
   Gambia = 'GM',
   Georgia = 'GE',
   Germany = 'DE',
   Ghana = 'GH',
   Gibraltar = 'GI',
   Greece = 'GR',
   Greenland = 'GL',
   Grenada = 'GD',
   Guadeloupe = 'GP',
   Guam = 'GU',
   Guatemala = 'GT',
   Guernsey = 'GG',
   Guinea = 'GN',
   'Guinea Bissau' = 'GW',
   Guyana = 'GY',
   Haiti = 'HT',
   'Heard Island And Mcdonald Islands' = 'HM',
   'Holy See Vatican City State' = 'VA',
   Honduras = 'HN',
   'Hong Kong' = 'HK',
   Hungary = 'HU',
   Iceland = 'IS',
   India = 'IN',
   Indonesia = 'ID',
   'Iran' = 'IR',
   Iraq = 'IQ',
   Ireland = 'IE',
   'Isle of Man' = 'IM',
   Israel = 'IL',
   Italy = 'IT',
   Jamaica = 'JM',
   Japan = 'JP',
   Jersey = 'JE',
   Jordan = 'JO',
   Kazakhstan = 'KZ',
   Kenya = 'KE',
   Kiribati = 'KI',
   'North Korea' = 'KP',
   'South Korea' = 'KR',
   Kosovo = 'XK',
   Kuwait = 'KW',
   Kyrgyzstan = 'KG',
   'Lao Peoples Democratic Republic' = 'LA',
   Latvia = 'LV',
   Lebanon = 'LB',
   Lesotho = 'LS',
   Liberia = 'LR',
   'Libya' = 'LY',
   Liechtenstein = 'LI',
   Lithuania = 'LT',
   Luxembourg = 'LU',
   Macao = 'MO',
   'Macedonia The Former Yugoslav Republic Of' = 'MK',
   Madagascar = 'MG',
   Malawi = 'MW',
   Malaysia = 'MY',
   Maldives = 'MV',
   Mali = 'ML',
   Malta = 'MT',
   'Marshall Islands' = 'MH',
   Martinique = 'MQ',
   Mauritania = 'MR',
   Mauritius = 'MU',
   Mayotte = 'YT',
   Mexico = 'MX',
   'Micronesia' = 'FM',
   'Moldova' = 'MD',
   Monaco = 'MC',
   Mongolia = 'MN',
   Montenegro = 'ME',
   Montserrat = 'MS',
   Morocco = 'MA',
   Mozambique = 'MZ',
   Myanmar = 'MM',
   Namibia = 'NA',
   Nauru = 'NR',
   Nepal = 'NP',
   Netherlands = 'NL',
   'Netherlands Antilles' = 'AN',
   'New Caledonia' = 'NC',
   'New Zealand' = 'NZ',
   Nicaragua = 'NI',
   Niger = 'NE',
   Nigeria = 'NG',
   Niue = 'NU',
   'Norfolk Island' = 'NF',
   'Northern Mariana Islands' = 'MP',
   Norway = 'NO',
   Oman = 'OM',
   Pakistan = 'PK',
   Palau = 'PW',
   'Palestine' = 'PS',
   Panama = 'PA',
   'Papua New Guinea' = 'PG',
   Paraguay = 'PY',
   Peru = 'PE',
   Philippines = 'PH',
   Pitcairn = 'PN',
   Poland = 'PL',
   Portugal = 'PT',
   'Puerto Rico' = 'PR',
   Qatar = 'QA',
   Reunion = 'RE',
   Romania = 'RO',
   'Russia' = 'RU',
   Rwanda = 'RW',
   'Saint Barthelemy' = 'BL',
   'Saint Helena' = 'SH',
   'Saint Kitts and Nevis' = 'KN',
   'Saint Lucia' = 'LC',
   'Saint Martin' = 'MF',
   'Saint Pierre And Miquelon' = 'PM',
   'Saint Vincent and the Grenadines' = 'VC',
   Samoa = 'WS',
   'San Marino' = 'SM',
   'Sao Tome and Principe' = 'ST',
   'Saudi Arabia' = 'SA',
   Senegal = 'SN',
   Serbia = 'RS',
   'Serbia And Montenegro' = 'CS',
   Seychelles = 'SC',
   'Sierra Leone' = 'SL',
   Singapore = 'SG',
   'Sint Maarten' = 'SX',
   Slovakia = 'SK',
   Slovenia = 'SI',
   'Solomon Islands' = 'SB',
   Somalia = 'SO',
   'South Africa' = 'ZA',
   'South Georgia And the South Sandwich Islands' = 'GS',
   'South Sudan' = 'SS',
   Spain = 'ES',
   'Sri Lanka' = 'LK',
   Sudan = 'SD',
   Suriname = 'SR',
   'Svalbard And Jan Mayen' = 'SJ',
   Swaziland = 'SZ',
   Sweden = 'SE',
   Switzerland = 'CH',
   'Syria' = 'SY',
   'Taiwan Province Of China' = 'TW',
   Tajikistan = 'TJ',
   'Tanzania' = 'TZ',
   Thailand = 'TH',
   'Timor-Leste' = 'TL',
   Togo = 'TG',
   Tokelau = 'TK',
   Tonga = 'TO',
   'Trinidad and Tobago' = 'TT',
   Tunisia = 'TN',
   Turkey = 'TR',
   Turkmenistan = 'TM',
   'Turks And Caicos Islands' = 'TC',
   Tuvalu = 'TV',
   Uganda = 'UG',
   Ukraine = 'UA',
   'United Arab Emirates' = 'AE',
   'United Kingdom' = 'GB',
   'United States' = 'US',
   'United States Minor Outlying Islands' = 'UM',
   Uruguay = 'UY',
   Uzbekistan = 'UZ',
   Vanuatu = 'VU',
   Venezuela = 'VE',
   Vietnam = 'VN',
   'Virgin Islands British' = 'VG',
   'Virgin Islands US' = 'VI',
   'Wallis And Futuna' = 'WF',
   'Western Sahara' = 'EH',
   Yemen = 'YE',
   Zambia = 'ZM',
   Zimbabwe = 'ZW',
}

export enum Continent {
   'Europe' = 'Europe',
   'North America' = 'North America',
   'South America' = 'South America',
   'Oceania' = 'Oceania',
   'Asia' = 'Asia',
   'Africa' = 'Africa',
   'Antartica' = 'Antartica',
}

export const EUROPE_LOCATIONS: (keyof typeof Location)[] = [
   'Albania',
   'Andorra',
   'Austria',
   'Belarus',
   'Belgium',
   'Bosnia and Herzegovina',
   'Bulgaria',
   'Croatia',
   'Cyprus',
   'Czech Republic',
   'Denmark',
   'Estonia',
   'Faroe Islands',
   'Finland',
   'France',
   'Germany',
   'Greece',
   'Guernsey',
   'Hungary',
   'Iceland',
   'Ireland',
   'Isle of Man',
   'Italy',
   'Jersey',
   'Kosovo',
   'Latvia',
   'Liechtenstein',
   'Lithuania',
   'Luxembourg',
   'Malta',
   'Moldova',
   'Monaco',
   'Montenegro',
   'Netherlands',
   'Norway',
   'Poland',
   'Portugal',
   'Romania',
   'Russia',
   'San Marino',
   'Serbia',
   'Slovakia',
   'Slovenia',
   'Spain',
   'Sweden',
   'Switzerland',
   'Ukraine',
   'United Kingdom',
];

export const ASIA_LOCATIONS: (keyof typeof Location)[] = [
   'Afghanistan',
   'Armenia',
   'Azerbaijan',
   'Bahrain',
   'Bangladesh',
   'Bhutan',
   'Brunei',
   'Cambodia',
   'China',
   'Cyprus',
   'Georgia',
   'India',
   'Indonesia',
   'Iran',
   'Iraq',
   'Israel',
   'Japan',
   'Jordan',
   'Kazakhstan',
   'Kuwait',
   'Kyrgyzstan',
   'Lebanon',
   'Malaysia',
   'Maldives',
   'Mongolia',
   'Myanmar',
   'Nepal',
   'North Korea',
   'Oman',
   'Pakistan',
   'Palestine',
   'Philippines',
   'Qatar',
   'Russia',
   'Saudi Arabia',
   'Singapore',
   'South Korea',
   'Sri Lanka',
   'Syria',
   'Tajikistan',
   'Thailand',
   'Timor-Leste',
   'Turkey',
   'Turkmenistan',
   'United Arab Emirates',
   'Uzbekistan',
   'Vietnam',
   'Yemen',
];

export const AFRICA_LOCATIONS: (keyof typeof Location)[] = [
   'Algeria',
   'Angola',
   'Benin',
   'Botswana',
   'Burkina Faso',
   'Burundi',
   'Cameroon',
   'Cape Verde',
   'Central African Republic',
   'Chad',
   'Comoros',
   'Congo',
   'Democratic Republic of Congo',
   "Cote d'Ivoire",
   'Djibouti',
   'Egypt',
   'Equatorial Guinea',
   'Eritrea',
   'Swaziland',
   'Ethiopia',
   'Gabon',
   'Gambia',
   'Ghana',
   'Guinea',
   'Guinea Bissau',
   'Kenya',
   'Lesotho',
   'Liberia',
   'Libya',
   'Madagascar',
   'Malawi',
   'Mali',
   'Mauritania',
   'Mauritius',
   'Morocco',
   'Mozambique',
   'Namibia',
   'Niger',
   'Nigeria',
   'Rwanda',
   'Sao Tome and Principe',
   'Senegal',
   'Seychelles',
   'Sierra Leone',
   'Somalia',
   'South Africa',
   'South Sudan',
   'Sudan',
   'Tanzania',
   'Togo',
   'Tunisia',
   'Uganda',
   'Zambia',
   'Zimbabwe',
];

export const NORTH_AMERICA_LOCATIONS: (keyof typeof Location)[] = [
   'Antigua and Barbuda',
   'Bahamas',
   'Barbados',
   'Belize',
   'Canada',
   'Costa Rica',
   'Cuba',
   'Dominica',
   'Dominican Republic',
   'El Salvador',
   'Grenada',
   'Guatemala',
   'Haiti',
   'Honduras',
   'Jamaica',
   'Mexico',
   'Nicaragua',
   'Panama',
   'Saint Kitts and Nevis',
   'Saint Lucia',
   'Saint Vincent and the Grenadines',
   'Trinidad and Tobago',
   'United States',
   'United States Minor Outlying Islands',
];

export const OCEANIA_LOCATIONS: (keyof typeof Location)[] = [
   'Australia',
   'Fiji',
   'Kiribati',
   'Marshall Islands',
   'Micronesia',
   'Nauru',
   'New Zealand',
   'Palau',
   'Papua New Guinea',
   'Samoa',
   'Solomon Islands',
   'Tonga',
   'Tuvalu',
   'Vanuatu',
];

export const SOUTH_AMERICA_LOCATIONS: (keyof typeof Location)[] = [
   'Argentina',
   'Bolivia',
   'Brazil',
   'Chile',
   'Colombia',
   'Ecuador',
   'Guyana',
   'Paraguay',
   'Peru',
   'Suriname',
   'Uruguay',
   'Venezuela',
];
