import { MigrationInterface, QueryRunner } from "typeorm"

export class enum1680310012106 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {

        await queryRunner.query(`INSERT INTO industry (id, name) VALUES
                                                                       (1, 'Advanced Materials'),
                                                                       (2, 'Advertising (AdTech)'),
                                                                       (3, 'AgTech (FarmTech)'),
                                                                       (4, 'Aerospace & Defense'),
                                                                       (5, 'Artificial Intelligence & Machine Learning (AI/ML)'),
                                                                       (6, 'Apps'),
                                                                       (7, 'Augmented & Virtual Reality (AR/VR)'),
                                                                       (8, 'AudioTech'),
                                                                       (9, 'B2C'),
                                                                       (10, 'Beauty'),
                                                                       (11, 'B2B'),
                                                                       (12, 'Big Data & Analytics'),
                                                                       (13, 'BioTech'),
                                                                       (14, 'Black / African American Founded'),
                                                                       (15, 'Business Products & Services'),
                                                                       (16, 'Cannabis'),
                                                                       (17, 'Chemicals & Materials'),
                                                                       (18, 'ClimateTech & CleanTech'),
                                                                       (19, 'CloudTech'),
                                                                       (20, 'Cloud Security'),
                                                                       (21, 'CMS'),
                                                                       (22, 'Collaboration'),
                                                                       (23, 'Communications Infrastructure'),
                                                                       (24, 'Community'),
                                                                       (25, 'Computers'),
                                                                       (26, 'Construction Tech'),
                                                                       (27, 'Consulting'),
                                                                       (28, 'Consumer'),
                                                                       (29, 'Consumer Electronics'),
                                                                       (30, 'Consumer Goods'),
                                                                       (31, 'Consumer Internet'),
                                                                       (32, 'CPG'),
                                                                       (33, 'Creator Economy'),
                                                                       (34, 'CRM'),
                                                                       (35, 'Cryptocurrency / Blockchain'),
                                                                       (36, 'Cybersecurity'),
                                                                       (37, 'Customer Service'),
                                                                       (38, 'D2C'),
                                                                       (39, 'DeepTech'),
                                                                       (40, 'Delivery'),
                                                                       (41, 'Developer Tools'),
                                                                       (42, 'Distribution & Retailing'),
                                                                       (43, 'Diversified'),
                                                                       (44, 'Entertainment & Media'),
                                                                       (45, 'E-Commerce'),
                                                                       (46, 'EdTech'),
                                                                       (47, 'Eldercare'),
                                                                       (48, 'Energy'),
                                                                       (49, 'Enterprise'),
                                                                       (50, 'Entertainment'),
                                                                       (51, 'E-Sports (Gaming)'),
                                                                       (52, 'Events'),
                                                                       (53, 'Environment'),
                                                                       (54, 'Fashion'),
                                                                       (55, 'FemTech'),
                                                                       (56, 'FinTech'),
                                                                       (57, 'Food and Beverage'),
                                                                       (58, 'Future of Work'),
                                                                       (59, 'GovTech'),
                                                                       (60, 'Hardware'),
                                                                       (61, 'Healthcare'),
                                                                       (62, 'Health & Wellbeing'),
                                                                       (63, 'Hospitality'),
                                                                       (64, 'HR Tech'),
                                                                       (65, 'Impact Investing'),
                                                                       (66, 'Industrials'),
                                                                       (67, 'Information Technology'),
                                                                       (68, 'Infrastructure'),
                                                                       (69, 'InsurTech'),
                                                                       (70, 'Internet'),
                                                                       (71, 'IoT (Internet of Things)'),
                                                                       (72, 'IT Services'),
                                                                       (73, 'Legal Tech'),
                                                                       (74, 'Life Science'),
                                                                       (75, 'Logistics'),
                                                                       (76, 'Manufacturing'),
                                                                       (77, 'Marketing (MarTech)'),
                                                                       (78, 'Marketplace'),
                                                                       (79, 'Market Research'),
                                                                       (80, 'Medical Device'),
                                                                       (81, 'Meeting Software'),
                                                                       (82, 'Micro-Mobility'),
                                                                       (83, 'Mobile'),
                                                                       (84, 'Nanotechnology'),
                                                                       (85, 'Network Security'),
                                                                       (86, 'Neuroscience'),
                                                                       (87, 'Oil & Gas'),
                                                                       (88, 'Travel'),
                                                                       (89, 'PaaS (Platforms)'),
                                                                       (90, 'Parenting'),
                                                                       (91, 'PetTech'),
                                                                       (92, 'Pharmaceuticals'),
                                                                       (93, 'POS (Point Of Sale)'),
                                                                       (94, 'Privacy'),
                                                                       (95, 'Professional Services'),
                                                                       (96, 'Productivity Tools'),
                                                                       (97, 'PropTech'),
                                                                       (98, 'Quality Assurance'),
                                                                       (99, 'Real Estate & Construction'),
                                                                       (100, 'RestaurantTech'),
                                                                       (101, 'Recruiting'),
                                                                       (102, 'RetailTech'),
                                                                       (103, 'Robotics'),
                                                                       (104, 'Ridesharing'),
                                                                       (105, 'SAAS'),
                                                                       (106, 'Sales Automation'),
                                                                       (107, 'Seervice Industry'),
                                                                       (108, 'Semiconductors'),
                                                                       (109, 'Sharing Economy'),
                                                                       (110, 'Social Media'),
                                                                       (111, 'Software'),
                                                                       (112, 'SpaceTech'),
                                                                       (113, 'Sports'),
                                                                       (114, 'Supply Chain Tech'),
                                                                       (115, 'Sustainability'),
                                                                       (116, 'Telecommunications'),
                                                                       (117, 'Telecommunications (TMT)'),
                                                                       (118, 'Transportation'),
                                                                       (119, 'Wearables & Quantified Self'),
                                                                       (120, 'Women-Founded');`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
